### ISSUE TITLE
Mettre en gras les différents items du menu

### ISSUE THREAD

**Issue by baudoliver7** [gap-enterprise/web-base#1]
Il faut mettre en gras les différents items du menu (Accueil, Paiements, Compte de gestion, etc.)

Cc: @Amone108

**Comment by Amone108** [comment]
Dans l'onglet Compte de Gestion, il faut transformer le sous-titre  Suivre
l'exécution des dépenses en ''Suivie de l'exécution des paiements''.
Il faudrait selon l'organisation et le fonctionnement du Trésor en
connexion avec le ministre du budget, probablement changer ''Suivie de
l'exécution des paiements'' en Suivie de l'exécution du budget, voire créer
un module dédié et appelé ''Suivie de l'exécution du budget''.

Bon courage.

Le lun. 21 mars 2022 à 10:19, Olivier B. OURA ***@***.***> a
écrit :

**Comment by baudoliver7** [comment]
Résolu
